name       : lucene++
version    : 3.0.7
release    : 6
source     :
    - https://github.com/luceneplusplus/LucenePlusPlus/archive/rel_3.0.7.tar.gz : 6c19f203311e4b44a0ccf7b1127db77436eb47159ea1c54f7531a0b1ca585e0c
license    :
    - LGPL-2.0
    - Apache-2.0
component  : programming
summary    : C++ port of the popular Java Lucene library
description: |
    Lucene++ is an up to date C++ port of the popular Java Lucene library, a high-performance, full-featured text search engine.
builddeps  :
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/boost-1.58.patch
    mkdir build
    cd build
    %cmake ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
